#!/bin/bash


Name=e2d_mgr_ctrl@127.0.0.1
CommPrefix='e2dmgr-'
Server=$1
if [ -z ${Server} ]; then
   echo -e "please specify the master server name"
   exit 1
fi
All=$@
Args=${All#* -}

erl -name ${Name} \
    -noinput \
    -s e2d_mgr_ctrl handle \
    -${CommPrefix}server ${Server} \
    -${CommPrefix}Args
