{application, crontab,
  [{description,
    "crontab description"},
   {vsn,          "1.0.0"},
   {modules,      [crontab,
	           crontab_server,
                   crontab_parse,
	           crontab_ctl,
	           dynamic_compile,
	           erl_logger_h,
	           erl_loglevel]},
   {registered,   [crontab]},
   {applications, [kernel, stdlib]},
   {mod, {crontab,[]}}]}.
