{application, balance,
  [{description,
    "balance description"},
   {vsn,          "1.0.0"},
   {modules,      [balance,
                   bal_sup,
	           bal_proxy,
                   tcp_proxy,
	           tcpbalance_ctl,
	           dynamic_compile,
	           erl_logger_h,
	           erl_loglevel]},
   {registered,   [bal_proxy,
	           balance_sup]},
   {applications, [kernel, stdlib]},
   {mod, {balance,[]}}]}.
