#!/bin/sh

###########################
# Configuration
###########################

ERL=erl
HOST=localhost

SETCOOKIE="setyourcookiehere"

POLL=true
SMP=auto
ERL_PROCESSES=2500000
ERL_MAX_PORTS=320000
ERL_MAX_ETS_TABLES=14000

###########################
# End of configuration
###########################


MYAPP=sysmon
NODE=$MYAPP@$HOST
NAME=-sname
ROOT="`dirname "$0"`"
ROOT="`cd "$ROOT"/.. && pwd`"

ERLANG_OPTS="+K $POLL -smp $SMP +P $ERL_PROCESSES" 

# define additional environment variables 
MYAPP_CONFIG_PATH=$ROOT/etc/sysmon.cfg 
MYAPP_LOG_PATH=$ROOT/log/sysmon.log 
SASL_LOG_PATH=$ROOT/log/sasl.log 
DATETIME=`date "+%Y%m%d-%H%M%S"`
ERL_CRASH_DUMP=$ROOT/log/erl_crash_$DATETIME.dump 

# export global variables 
export MYAPP_CONFIG_PATH 
export MYAPP_LOG_PATH 
export SASL_LOG_PATH
export ERL_CRASH_DUMP 
export ERL_MAX_PORTS
export ERL_MAX_ETS_TABLES

case "$1" in
  start)
	 $ERL -noinput -detached $NAME $NODE \
           $ERLANG_OPTS \
           -pa "$ROOT/ebin" -pa "$ROOT/deps/exmpp-0.9.3/ebin" -s sysmon start \
           -mnesia dir \""$ROOT/database"\" \
	   -setcookie $SETCOOKIE \
           -sasl sasl_error_logger \{file,\"$SASL_LOG_PATH\"\} 
	 ;;
  debug)
         echo "Press any key to continue" 
         read foo 
         $ERL $NAME sysmondebug@$HOST -remsh $NODE \
           -setcookie $SETCOOKIE \
           -pa "$ROOT/ebin" -pa "$ROOT/deps/exmpp-0.9.3/ebin"
         ;;
      *)
         $ERL -noinput $NAME sysmonctl@$HOST \
           -setcookie $SETCOOKIE \
           -pa "$ROOT/ebin" -pa "$ROOT/deps/exmpp-0.9.3/ebin" -s sysmon_ctl -extra $NODE $@
         ;;
esac
