#!/bin/sh

ROOTDIR=/home/liqiang/dev/ejabberd/qiang/dev3/dispatchserver

# define default configuration
POLL=true
SMP=auto
ERL_PROCESSES=2500000
ERL_MAX_PORTS=320000
ERL_MAX_ETS_TABLES=14000

# define default enviroment variables
NODE=dispatchserver
HOST=localhost
ERLANG_NODE=$NODE@$HOST
ERL=/usr/bin/erl
NAME=-sname

# parse command line parameters
ARGS=
while [ $# -ne 0 ] ; do
  PARAM=$1
  shift
  case $PARAM in
    --) break ;;
    --node) ERLANG_NODE=$1 ; shift ;;
    --config) DISPATCHSERVER_CONFIG_PATH=$1 ; shift ;;
    --logs) LOGS_DIR=$1 ; shift ;;
    *) ARGS="$ARGS $PARAM" ;;
  esac
done

# define dispatchserver variable if they have not been defined from comand line
if [ "$DISPATCHSERVER_CONFIG_PATH" = "" ] ; then
  DISPATCHSERVER_CONFIG_PATH=$ROOTDIR/etc/dispatchserver.cfg
fi
if [ "$LOGS_DIR" = "" ] ; then
  LOGS_DIR=$ROOTDIR/log
fi

ERLANG_OPTS="+K $POLL -smp $SMP +P $ERL_PROCESSES" 

# define additional environment variables 
DISPATCHSERVER_EBIN=$ROOTDIR/ebin 
DISPATCHSERVER_LOG_PATH=$LOGS_DIR/dispatchserver.log 
SASL_LOG_PATH=$LOGS_DIR/sasl.log 
DATETIME=`date "+%Y%m%d-%H%M%S"`
ERL_CRASH_DUMP=$LOGS_DIR/erl_crash_$DATETIME.dump 

# export global variables 
export DISPATCHSERVER_CONFIG_PATH 
export DISPATCHSERVER_LOG_PATH 
export SASL_LOG_PATH
export ERL_CRASH_DUMP 
export ERL_MAX_PORTS
export ERL_MAX_ETS_TABLES
# start server 
start () 
{ 
    $ERL \
      $NAME $ERLANG_NODE \
      -noinput -detached \
      -pa $DISPATCHSERVER_EBIN \
      -s ds \
      -sasl sasl_error_logger \{file,\"$SASL_LOG_PATH\"\} \
      $ERLANG_OPTS $ARGS "$@" 
} 

# attach to server 
debug () 
{ 
    echo "--------------------------------------------------------------------" 
    echo "" 
    echo "IMPORTANT: we will attempt to attach an INTERACTIVE shell" 
    echo "to an already running dispatchserver node." 
    echo "If an ERROR is printed, it means the connection was not succesfull." 
    echo "You can interact with the dispatchserver node if you know how to use it." 
    echo "Please be extremely cautious with your actions," 
    echo "and exit immediately if you are not completely sure." 
    echo "" 
    echo "To detach this shell from dispatchserver, press:" 
    echo "  control+c, control+c" 
    echo "" 
    echo "--------------------------------------------------------------------" 
    echo "Press any key to continue" 
    read foo 
    echo "" 
    $ERL \
      $NAME ${NODE}debug \
      -remsh $ERLANG_NODE \
      $ERLANG_OPTS $ARGS "$@" 
} 

# start interactive server 
live () 
{ 
    echo "--------------------------------------------------------------------" 
    echo "" 
    echo "IMPORTANT: dispatchserver is going to start in LIVE (interactive) mode." 
    echo "All log messages will be shown in the command shell." 
    echo "You can interact with the dispatchserver node if you know how to use it." 
    echo "Please be extremely cautious with your actions," 
    echo "and exit immediately if you are not completely sure." 
    echo "" 
    echo "To exit this LIVE mode and stop dispatchserver, press:" 
    echo "  q().  and press the Enter key" 
    echo "" 
    echo "--------------------------------------------------------------------" 
    echo "Press any key to continue" 
    read foo 
    echo "" 
    $ERL \
      $NAME $ERLANG_NODE \
      -pa $DISPATCHSERVER_EBIN \
      -s ds \
      $ERLANG_OPTS $ARGS "$@" 
} 

# common control function 
ctl () 
{ 
    $ERL \
      $NAME dsctl \
      -noinput \
      -pa $DISPATCHSERVER_EBIN \
      -s dsctl -extra $ERLANG_NODE $@ 
    result=$? 
    case $result in 
    0) :;; 
    *) 
        echo "" 
        echo "Commands to start an dispatchserver node:" 
        echo "  start  Start an dispatchserver node in server mode" 
        echo "  debug  Attach an interactive Erlang shell to a running dispatchserver node" 
        echo "  live   Start an dispatchserver node in live (interactive) mode" 
        echo "" 
        echo "Optional parameters when starting an dispatchserver node:" 
        echo "  --config file      Config file of dispatchserver:     $DISPATCHSERVER_CONFIG_PATH" 
        echo "  --logs dir         Directory for logs:                $LOGS_DIR" 
        echo "  --node nodename    dispatchserver node name:          $ERLANG_NODE" 
        echo "";; 
    esac 
    return $result 
} 

# display ctl usage 
usage () 
{ 
    ctl 
    exit 
} 

case $ARGS in 
    ' start') start;; 
    ' debug') debug;; 
    ' live') live;; 
    *) ctl $ARGS;; 
esac 
