#!/usr/bin/env escript
%% -*- mode: erlang -*-
-export([main/1]).

%% External API

%% Controller:string()
main(["controller", Controller]) ->
    ensure(),
    BaseDir = skel_deps:get_base_dir(),
    erails_gen:new_controller(BaseDir, Controller, "skel");
main(["model", _Model]) ->
    ensure(),
    io:format("did not implement the command!~n", []);
main(_) ->
    usage().

%% Internal API

ensure() ->
    code:add_patha(filename:join(filename:dirname(escript:script_name()),
                                 "../ebin")),
    code:add_patha(filename:join(filename:dirname(escript:script_name()),
                                 "../deps/erlangonrails/ebin")).

usage() ->
    io:format("usage: ~s [controller|model] [Name]~n",
              [filename:basename(escript:script_name())]),
    halt(1).
