%% ---------------------------------
%% Logging mechanism
%%
%% loglevel: Verbosity of log files generated by  dispatch server.
%% 0: No  dispatch server log at all (not recommended)
%% 1: Critical
%% 2: Error
%% 3: Warning
%% 4: Info
%% 5: Debug
%%---------------------------------

-define(SETUP_LOG(Path), 
    error_logger:add_report_handler(erl_logger_h, Path)).

-define(SET_LOG_LEVEL(Level),
    erl_loglevel:set(Level)).

%% Print in standard output
-define(PRINT(Format, Args),
    io:format(Format, Args)).

-define(DEBUG(Format, Args),
    erl_logger:debug_msg(?MODULE,?LINE,Format, Args)).

-define(INFO_MSG(Format, Args),
    erl_logger:info_msg(?MODULE,?LINE,Format, Args)).
			      
-define(WARNING_MSG(Format, Args),
    erl_logger:warning_msg(?MODULE,?LINE,Format, Args)).
			      
-define(ERROR_MSG(Format, Args),
    erl_logger:error_msg(?MODULE,?LINE,Format, Args)).

-define(CRITICAL_MSG(Format, Args),
    erl_logger:critical_msg(?MODULE,?LINE,Format, Args)).

